### ISSUE TITLE
Isolate DB operations inside a class

### ISSUE THREAD

**Issue by qyom** [EminGrig/FixedFirstProject#1]
We will do the following refactoring.

Create a new file called db.php where you'll create a new class called Database.
It'll have 
- it's connection parameters as constants.
- the PDO resource object as a protected field of the class.
- A constructor that will setup the PDO object and assign to that protected field
- A method called fetchNamesByDay($day) that will return the list of names in array

refactor the index.php to use that class instead
;)

**Comment by EminGrig** [comment]
Done
